spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer-route
          uri: lb://CUSTOMER-SERVICE-PROVIDER
          predicates:
            - Path=/customer/**
          filters:
            - StripPrefix=1
        - id: order-route
          uri: lb://ORDER-SERVICE-PROVIDER
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix=1
        - id: jewellery-route
          uri: lb://JEWELLERY-SERVICE-PROVIDER
          predicates:
            - Path=/jewellery/**
          filters:
            - StripPrefix=1
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-Zone: http://localhost:8761/eureka
server:
  port: 8888
