spring:
  application:
    name: customer-service-provider
eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
         defaultZone: http://localhost:8761/eureka
server:
  port: 8992
